= Metriken

== Java-Bibliotheken

* http://metrics.dropwizard.io/[Dropwizard Metrics]
  (ursprünglich mal yammer metrics, dann codahale metrics, nun dropwizard metrics)

=== unterstützte Metriken

Gauge:: der einfachste Typ einer Metrik, hält einfach nur einen Wert zu einem bestimmten Zeitpunkt,
also bspw. die Anzahl der aktuellen DB-Verbindungen

Counter:: Typ zum In- oder Dekrement, also bspw. zum Zählen der Aufrufe einer Methode

Histogram:: Damit wird auch die Verteilung der Werte gespeichert, damit aus den Daten bspw. Percentilen ermittelt werden können

Meter:: Speicherung der Rate, also wie oft etwas in einem Zeitfenster geschieht (inkl. Berechnung der Durchschnittswerte
für vordefinierte Zeitfenster wie 1, 5 und 15 Minuten)

Timer:: Messung der Ausführungsdauer

== Metrik-Datenbanken

(Time-Series-Datenbanken, Round-Robin-Datenbanken)

* https://graphiteapp.org/[Graphite]
* http://ganglia.sourceforge.net/[Ganglia]
* https://www.influxdata.com/[influxDB]
* https://prometheus.io/[Prometheus]
* http://basho.com/products/riak-ts/[Riak TS]
* http://opentsdb.net/[OpenTSDB]
* ...

== Visualisierung

* https://grafana.com/[Grafana]
* https://www.elastic.co/de/products/kibana[Kibana]
* integrierte Dashboards

== Demo PetClinic

Nutzt Graphite und Grafana, da für diese Kombination zur Zeit die umfassendste Unterstützung besteht,
die meisten Projekte, die irgendwie Metriken erfassen, stellen diese - wenn nicht eh über Dropwizard -
über Graphite oder JMX bereit.

* `docker-compose up` zum Start der MySQL und des Graphite/Grafana-Server
* `mvn spring-boot:run` zum Start der Anwendung
* `.../jmeter -n -t load.jmx` zur Ausführung des Lasttests, um Metrike-Werte zu erzeugen

== weitere Themen

* Request-Tracing (Request-Verfolgung über mehrere Anwendungen hinweg) wie
** http://zipkin.io/[Zipkin]
** https://cloud.spring.io/spring-cloud-sleuth/[Spring Cloud Sleuth]
* Schwellenwerte, Alarmierung, ...

== URLs Demo

* http://localhost:8080/[Demo]
* http://localhost:10080/[Grafana]
* http://localhost:10081/[Graphite-UI]
